# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  install:
    aliases: [i]
    cmds:
      - npm install --force
  build:
    aliases: [b]
    cmds:
      - npm run build
  build:faster:
    summary: |
      Build without MDX preprocessing.

      HHGC AEG has only recently migrated from Mozilla Mach, so, for convenience, the base syntax has remained identical to `mach build faster`
    aliases: [f]
    cmds:
      - npm run build
  preview:
    aliases: [p]
    cmds:
      - npm run preview
  dev:
    aliases: [d]
    cmds:
      - npm run dev
