# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
  install:
    aliases: [i]
    cmds:
      - uv venv  --python-preference only-managed --python 3.13 .venv
      - npm install --force
  build:preprocess:
    description: Preprocess templated MDX files
    cmds:
      - |
        uv run python ./mdx-worker.py \
        --root-dir ./src/lib/sixth-chamber/doc \
        --output-dir ./src/lib/mawanet \
        --whitelist ./src/lib/sixth-chamber/whitelist.json
  build:
    aliases: [b]
    cmds:
      - task: build:preprocess
      - npm run build
  build:faster:
    summary: |
      Build without MDX preprocessing.

      HHGC AEG has only recently migrated from Mozilla Mach, so, for convenience, the base syntax has remained identical to `mach build faster`
    aliases: [f]
    cmds:
      - npm run build
  preview:
    aliases: [p]
    cmds:
      - npm run preview
  dev:
    aliases: [d]
    cmds:
      # - task: build:preprocess
      - npm run dev
