on:
  # run manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          token: ${{ secrets.MTT_SIXTH_CHAMBER_PAT }}
          submodules: true

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: lts/*
          cache: "npm"
      - name: Set up Node dependencies
        # see https://github.com/lorikayman/lorikayman.github.io/issues/12
        # see https://github.com/standard/eslint-config-standard/issues/427
        # see https://github.com/standard/eslint-config-standard/issues/411
        #
        # we use --force due to standard/eslint-config-standard `eslint` dependency compatibility having a stroke
        run: npm install --force

      # https://taskfile.dev/installation/#github-actions
      - uses: arduino/setup-task@v2
        name: Set up Task runner
        with:
          version: 3.x

      - name: Build with Task
        run: task build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
